const noteArray = [
  { keys: ["a#/3"], duration: "q", accidental: "#" },
  { keys: ["b/3"], duration: "q" },
  { keys: ["c/4"], duration: "q" },
  { keys: ["c#/4"], duration: "q", accidental: "#" },
  { keys: ["d/4"], duration: "q" },
  { keys: ["d#/4"], duration: "q", accidental: "#" },
  { keys: ["e/4"], duration: "q" },
  { keys: ["f/4"], duration: "q" },
  { keys: ["f#/4"], duration: "q", accidental: "#" },
  { keys: ["g/4"], duration: "q" },
  { keys: ["g#/4"], duration: "q", accidental: "#" },
  { keys: ["a/4"], duration: "q" },
  { keys: ["a#/4"], duration: "q", accidental: "#" },
  { keys: ["b/4"], duration: "q" },
  { keys: ["b/4"], duration: "q" },
  { keys: ["c/5"], duration: "q" },
  { keys: ["c/5"], duration: "q" },
  { keys: ["c#/5"], duration: "q", accidental: "#" },
  { keys: ["d/5"], duration: "q" },
  { keys: ["d#/5"], duration: "q", accidental: "#" },
  { keys: ["e/5"], duration: "q" },
  { keys: ["f/5"], duration: "q" },
  { keys: ["f#/5"], duration: "q", accidental: "#" },
  { keys: ["g/5"], duration: "q" },
  { keys: ["g#/5"], duration: "q", accidental: "#" },
  { keys: ["a/5"], duration: "q" },
  { keys: ["a#/5"], duration: "q", accidental: "#" },
  { keys: ["b/5"], duration: "q" },
  { keys: ["c/6"], duration: "q" },
  { keys: ["c#/6"], duration: "q", accidental: "#" },
  { keys: ["d/6"], duration: "q" },
  { keys: ["d#/6"], duration: "q", accidental: "#" },
  { keys: ["e/6"], duration: "q" },
  { keys: ["f/6"], duration: "q" },
  { keys: ["f#/6"], duration: "q", accidental: "#" },
];

export default noteArray;
